AWSTemplateFormatVersion: 2010-09-09
Description: "elastic load balancer with two EC2 instances, public and private VPC"

Resources: 
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/26"
      EnableDnsSupport: true

  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId: !Ref vpc
      CidrBlock: "10.0.0.0/28"
      MapPublicIpOnLaunch: false

  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId: !Ref vpc
      CidrBlock: "10.0.0.16/28"
      MapPublicIpOnLaunch: true

  internetGateway:
    Type: AWS::EC2::InternetGateway

  attachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpc
      InternetGatewayId: !Ref internetGateway
    
  natElasticIp:
    Type: AWS::EC2::EIP
    DependsOn: attachGateway
    Properties:
      Domain: vpc

  natGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt natElasticIp.AllocationId
      SubnetId: !Ref publicSubnet

  

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref vpc

  PublicSubnet:
    Description: Public subnet
    Value: !Ref publicSubnet

  PrivateSubnet:
    Description: Private subnet
    Value: !Ref privateSubnet
