AWSTemplateFormatVersion: 2010-09-09
Description: >
  "elastic load balancer with two EC2 instances, public and private VPC."

Resources: 
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/26"
      EnableDnsSupport: true

  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId: !Ref vpc
      CidrBlock: "10.0.0.0/28"
      MapPublicIpOnLaunch: false

  publicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId: !Ref vpc
      CidrBlock: "10.0.0.16/28"
      MapPublicIpOnLaunch: true

  internetGateway:
    Type: AWS::EC2::InternetGateway

  attachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpc
      InternetGatewayId: !Ref internetGateway
    
  natElasticIp:
    Type: AWS::EC2::EIP
    DependsOn: attachGateway
    Properties:
      Domain: vpc

  natGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt natElasticIp.AllocationId
      SubnetId: !Ref publicSubnet

  sshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "sg-ssh"
      GroupDescription: "Enables SSH access via port 22"
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  httpSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "sg-http"
      GroupDescription: "Enables HTTP access via port 80"
      VpcId: !Ref vpc
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "ec2key"
      ImageId: "ami-091aa67fccd794d5f"
      InstanceType: "t2.micro"
      SecurityGroupIds: [
        !Ref sshSecurityGroup,
        !Ref httpSecurityGroup
      ]

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref vpc

  PublicSubnet:
    Description: Public subnet
    Value: !Ref publicSubnet

  PrivateSubnet:
    Description: Private subnet
    Value: !Ref privateSubnet
